name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npm install jest-junit --save-dev
    
    - name: Run tests with JUnit output
      id: tests
      run: |
        npx jest --ci --reporters=default --reporters=jest-junit --outputFile=junit.xml
    
    - name: Publish test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ github.run_id }}
        path: junit.xml
    
    - name: Run ESLint
      run: |
        npx eslint script.js -f html -o eslint-report.html --fix || echo "::warning::ESLint found issues"
    
    - name: Publish ESLint report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: eslint-report-${{ github.run_id }}
        path: eslint-report.html
    
    - name: Build project
      if: steps.tests.outcome == 'success'
      run: |
        mkdir -p dist
        cp *.html dist/
        cp *.css dist/
        cp *.js dist/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: steps.tests.outcome == 'success'
      with:
        name: website-build-${{ github.run_id }}
        path: dist/